/**
 * The Node constraint a generated pixi manifest declares.
 *
 * A bare `major` or `major.minor` becomes a `.*` range so the solve is free to take a patch release;
 * a version the author spelled out in full is written through unchanged, because someone who typed
 * `22.11.0` meant `22.11.0`.
 *
 * @param {string} runtimeVersion
 * @returns {{ name: string, spec: string }} the `[dependencies]` entry this runtime contributes
 */
export function pixiDependency(runtimeVersion: string): {
    name: string;
    spec: string;
};
/**
 * The JavaScript source `scrollcase new scroll --runtime node` writes for a project that has none.
 *
 * Same shape and same purpose as the Python starters next door: short enough to read in one screen,
 * and explicit about what the author is expected to replace. They are CommonJS because a box's
 * entry point is a path the runtime is handed rather than a package with a declared type, and
 * `node app.js` reads a file with no `package.json` beside it as CommonJS.
 */
/** The application a generated `node-script` scroll points at. */
export const STARTER_SCRIPT: "// Minimal application entry point generated by Scrollcase.\n\nfunction main() {\n  console.log('Scrollcase box is ready.');\n  return 0;\n}\n\nprocess.exitCode = main();\n";
/** The self-test a generated scroll runs with the box's own Node. */
export const STARTER_SELF_TEST: "// Self-test for this box, run by `scrollcase build` before the box is archived.\n//\n// It runs with the box's own Node, from the payload root, after the modules declared in scroll.json\n// have already loaded \u2014 so it can read the files the box ships and require the code it packs. A\n// thrown error fails the build, which is the point: this is the last check that the box works\n// before anyone downloads it.\n//\n// Replace the line below with something that would actually notice a broken box.\n\nconsole.log('self-test ok');\n";
