/**
 * The interpreter constraint a generated pixi manifest declares.
 *
 * A bare `major.minor` becomes `major.minor.*` so the solve is free to take a patch release; a
 * version the author spelled out in full is written through unchanged, because someone who typed
 * `3.14.2` meant `3.14.2`.
 *
 * @param {string} runtimeVersion
 * @returns {{ name: string, spec: string }} the `[dependencies]` entry this runtime contributes
 */
export function pixiDependency(runtimeVersion: string): {
    name: string;
    spec: string;
};
/**
 * The Python source `scrollcase new scroll` writes for a project that has none yet.
 *
 * These are starting points, not scaffolding to be extended: each is short enough to read in one
 * screen and says what the author is expected to replace. They live under the runtime because they
 * are Python source — a Node box or a native box needs different files, and the authoring path
 * should reach for the runtime's own rather than acquire a branch per runtime.
 */
/** The application a generated `python-script` scroll points at. */
export const STARTER_SCRIPT: "\"\"\"Minimal application entry point generated by Scrollcase.\"\"\"\n\nimport sys\n\n\ndef main() -> int:\n    print(\"Scrollcase box is ready.\")\n    return 0\n\n\nif __name__ == \"__main__\":\n    sys.exit(main())\n";
/** The self-test a generated scroll runs with the box's own interpreter. */
export const STARTER_SELF_TEST: "\"\"\"Self-test for this box, run by `scrollcase build` before the box is archived.\n\nIt runs with the box's own interpreter, from the payload root, after the imports declared in\nscroll.json have already succeeded \u2014 so it can read the files the box ships and import the code it\npacks. Any exception fails the build, which is the point: this is the last check that the box works\nbefore anyone downloads it.\n\nReplace the line below with something that would actually notice a broken box.\n\"\"\"\n\nprint(\"self-test ok\")\n";
